[package]
name = "module1"
version = "0.1.0"
edition = "2021"
authors = ["Alekzandev <aleksandev@proton.me>"]

[[bin]]
name = "module1"
path = "src/main.rs"

[dependencies]
calculator = { path = "modules/1"}