name: Clippy

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  profile: minimal
                  components: clippy, rustfmt
            - name: Run Clippy
              run: make lint